"""normalize question subject relationship

Revision ID: 2138e0663f64
Revises: d00df69711b5
Create Date: 2026-07-11 17:52:46.863060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2138e0663f64'
down_revision: Union[str, Sequence[str], None] = 'd00df69711b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question_bank', 'bank_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('question_bank', 'library_subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('question_bank', 'correct_answer',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('question_bank', 'subject',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint(op.f('question_bank_library_subject_id_fkey'), 'question_bank', type_='foreignkey')
    op.create_foreign_key(None, 'question_bank', 'question_library_subjects', ['library_subject_id'], ['library_subject_id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question_bank', type_='foreignkey')
    op.create_foreign_key(op.f('question_bank_library_subject_id_fkey'), 'question_bank', 'question_library_subjects', ['library_subject_id'], ['library_subject_id'], ondelete='SET NULL')
    op.alter_column('question_bank', 'subject',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('question_bank', 'correct_answer',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('question_bank', 'library_subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('question_bank', 'bank_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
