"""create exam questions table

Revision ID: 2150202ebdef
Revises: 0457ea2fcc50
Create Date: 2026-07-03 14:01:01.371388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2150202ebdef'
down_revision: Union[str, Sequence[str], None] = '0457ea2fcc50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exam_questions_id'), table_name='exam_questions')
    op.drop_table('exam_questions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_questions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('exam_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.exam_id'], name=op.f('exam_questions_exam_id_fkey')),
    sa.ForeignKeyConstraint(['question_id'], ['question_bank.questionbank_id'], name=op.f('exam_questions_question_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('exam_questions_pkey'))
    )
    op.create_index(op.f('ix_exam_questions_id'), 'exam_questions', ['id'], unique=False)
    # ### end Alembic commands ###
