"""add question library subjects

Revision ID: 2c1ac9b05176
Revises: d94b82831a04
Create Date: 2026-07-10 21:59:18.182382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c1ac9b05176'
down_revision: Union[str, Sequence[str], None] = 'd94b82831a04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_bank', sa.Column('library_subject_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_question_bank_bank_id'), 'question_bank', ['bank_id'], unique=False)
    op.create_index(op.f('ix_question_bank_library_subject_id'), 'question_bank', ['library_subject_id'], unique=False)
    op.drop_constraint(op.f('question_bank_bank_id_fkey'), 'question_bank', type_='foreignkey')
    op.create_foreign_key(None, 'question_bank', 'question_bank_sets', ['bank_id'], ['bank_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'question_bank', 'question_library_subjects', ['library_subject_id'], ['library_subject_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question_bank', type_='foreignkey')
    op.drop_constraint(None, 'question_bank', type_='foreignkey')
    op.create_foreign_key(op.f('question_bank_bank_id_fkey'), 'question_bank', 'question_bank_sets', ['bank_id'], ['bank_id'])
    op.drop_index(op.f('ix_question_bank_library_subject_id'), table_name='question_bank')
    op.drop_index(op.f('ix_question_bank_bank_id'), table_name='question_bank')
    op.drop_column('question_bank', 'library_subject_id')
    # ### end Alembic commands ###
