"""add bank id to questions

Revision ID: 3aa16446eb3e
Revises: 3f06682e378a
Create Date: 2026-07-09 11:22:07.168290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aa16446eb3e'
down_revision: Union[str, Sequence[str], None] = '3f06682e378a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_bank', sa.Column('bank_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'question_bank', 'question_bank_sets', ['bank_id'], ['bank_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question_bank', type_='foreignkey')
    op.drop_column('question_bank', 'bank_id')
    # ### end Alembic commands ###
