"""add extracted text to question imports

Revision ID: 6c245922f81b
Revises: 0eab04d62dfe
Create Date: 2026-07-14 23:17:22.453683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c245922f81b'
down_revision: Union[str, Sequence[str], None] = '0eab04d62dfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_imports', sa.Column('extracted_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_imports', 'extracted_text')
    # ### end Alembic commands ###
